version: '3.9'

services:
    node-boiler:
        container_name: node-boiler
        build:
            context: .
            target: production
        ports:
            - 3000:3000
        env_file:
            - .env
